baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hakkelademann'
theme = 'terminal'

[params]
    contentTypeName = "movies"
    themeColor = "green"
    fullWidthTheme = true

[languages]
    [languages.en.params.logo]
      logoText = "Hakkelademann"
      logoHomeLink = "/"