name: Fetch movies

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: $
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run npm install
        run: cd scripts && npm install && cd ..
      - name: Fetch movies
        run: node scripts/fetch-movie-data.js
        env:
          MOVIEDB_APIKEY: ${{ secrets.MOVIEDB_APIKEY }}
      - name: Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action-jackson@github.com"
          git add -A
          git commit -m "Update movie data"
          git push
