name: Fetch movies

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run npm install
        run: cd scripts && npm install && cd ..
      - name: Fetch movies
        run: node scripts/fetch-movie-data.js
        env:
          MOVIEDB_APIKEY: ${{ secrets.MOVIEDB_APIKEY }}
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git diff --staged --quiet || (git commit -m "Auto update movie data" && git push)
