name: Fetch movies

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run npm install
        run: cd scripts && npm install && cd ..
      - name: Fetch movies
        run: node scripts/fetch-movie-data.js
        env:
          MOVIEDB_APIKEY: ${{ secrets.MOVIEDB_APIKEY }}
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || git add . && git commit -m "Auto update movie data" && git push
